# Dockerfile.worker

FROM daskdev/dask:latest

# Instalación de dependencias, si es necesario
RUN apt-get update && apt-get install -y python3-pip

# Instalar dask y otras dependencias necesarias
RUN pip install dask distributed

# Configuración predeterminada para dask-worker
CMD ["dask-worker", "tcp://dask-master:8786", "--nthreads", "2", "--memory-limit", "auto"]
